
environmentName: 'prod'
server:
  Host: localhost
  Port: 50051
  ReadTimeout: 5
  WriteTimeout: 15
  IdleTimeout: 20
  
logger:
  base: logrus
  level: debug
  filename: cdp.log
  maxsize: 10
  maxage: 1
  maxbackups: 10
  localtime: true
  compress: false
  reportcaller: true

